spring:
  application:
    name: movie-reservation-system

  datasource:
    username: root
    password: quantuanhuy
    url: jdbc:mysql://localhost:3306/movie_reservation_system
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

    elasticsearch:
      rest:
        url: localhost:9200
        username: elastic
        password: elastic


  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
#      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

server:
  port: 5454

notification:
  email:
    brevo-url: https://api.brevo.com
    api-key: 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

app:
  security:
    jwt:
      secret: JHD2p1EolyuH3K6Gjz05onMO5hRT8CYHJHD2p1EolyuH3K6Gjz05onMO5hRT8CYH
      expiration: 86400000
      header: Authorization
      prefix: Bearer
    filter:
      publicUrls:
        - first: /api/v1/auth/login
          second: POST
        - first: /api/v1/auth/sign-up
          second: POST
        - first: /api/v1/movies
          second: GET
        - first: /api/v1/movies/\d+
          second: GET
        - first: /api/v1/cinemas
          second: GET
        - first: /api/v1/cinemas/\d+
          second: GET
        - first: /api/v1/genres/\d+
          second: GET
        - first: /api/v1/genres
          second: GET
        - first: /api/v1/cinemas/\d+/cinema_halls
          second: GET
        - first: /api/v1/cinema_hall_seats
          second: GET
        - first: /api/v1/cinemas/\d+/shows
          second: GET
        - first: /api/v1/shows
          second: GET
        - first: /api/v1/shows/\d+
          second: GET
        - first: /api/v1/seat_types
          second: GET
        - first: /api/v1/show_seats
          second: GET
      protectedUrls:
        - urlPattern: /api/v1/genres/*
          roles:
            - ADMIN
            - MODERATOR
        - urlPattern: /api/v1/movies/**
          roles:
            - ADMIN
            - MODERATOR
        - urlPattern: /api/v1/cinemas/*
          roles:
            - ADMIN
        - urlPattern: /api/v1/cinema_halls/*
          roles:
            - ADMIN
        - urlPattern: /api/v1/cinema_hall_seats/*
          roles:
            - ADMIN
            - MODERATOR
        - urlPattern: /api/v1/cinema_hall_seats/*
          roles:
            - ADMIN
        - urlPattern: /api/v1/shows/*
          roles:
            - ADMIN
        - urlPattern: /api/v1/seat_types/*
          roles:
            - ADMIN
            - MODERATOR
        - urlPattern: /api/v1/show_seats/*
          roles:
            - ADMIN
            - MODERATOR